// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnvgfhnbdgtspvwzyzhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudmdmaG5iZGd0c3B2d3p5emhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDYyOTgsImV4cCI6MjA3NDU4MjI5OH0.x28TbJSmZnDCLqP--Bd5o0p-pikbSx_Dmi8E4vaX2WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});